#!/usr/bin/env bash
#installs nginx web server, listening on port 80; dummy index page
apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.nginx.html
service nginx restart
