#!/usr/bin/env bash
# script that displays the content of the file /etc/passwd
# diplays username
# displays user id
# displays directory path for the user
file="/etc/passwd"

while IFS= read -r line
do
	echo "$line" | cut -d ":" -f 1,3,6
done < $file
