#!/usr/bin/env bash
# script that displays the content of the file /etc/passwd
file="/etc/passwd"

if [ -e "$file" ]
then
    # Use a while loop to read each line
    while IFS=: read -r username x uid gid gecos home shell; do
        # Display the formatted information
        echo "The user $username is part of the $gid gang, lives in $home, and rides $shell."
        echo "USER ID's place is protected by the passcode [PASSWORD], more info about the user here: $gecos"
    done < "$file"
else
    echo "Error: $file does not exist."
fi
